// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqE3Hnw4hrBB3KmoWST_61_OqLO9EOnUU',
    appId: '1:509023017607:web:fc37f27820643737627622',
    messagingSenderId: '509023017607',
    projectId: 'uas-21312107',
    authDomain: 'uas-21312107.firebaseapp.com',
    storageBucket: 'uas-21312107.appspot.com',
    measurementId: 'G-000NKCSQG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJG6dNnYUSaCZUyOaa_YS9LYFtYqW5bg',
    appId: '1:509023017607:android:f6be189a988b3601627622',
    messagingSenderId: '509023017607',
    projectId: 'uas-21312107',
    storageBucket: 'uas-21312107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoMwFjfA71b_TAqgOho0ILzM79lCsz3ow',
    appId: '1:509023017607:ios:d92b54218227a000627622',
    messagingSenderId: '509023017607',
    projectId: 'uas-21312107',
    storageBucket: 'uas-21312107.appspot.com',
    iosClientId: '509023017607-5kaok9h03chlg49a1s6bqtbirnjre0gu.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoMwFjfA71b_TAqgOho0ILzM79lCsz3ow',
    appId: '1:509023017607:ios:3c1aa3d71ba8d6e6627622',
    messagingSenderId: '509023017607',
    projectId: 'uas-21312107',
    storageBucket: 'uas-21312107.appspot.com',
    iosClientId: '509023017607-q405nrn7sh0gm8sn5vg39r0vpoj0i3eh.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet.RunnerTests',
  );
}
